[package]
name = "ssal-sequencer"
version = "0.1.0"
edition = "2021"

[dependencies]
ssal-commitment = { path = "../ssal-commitment" }
ssal-core = { path = "../ssal-core" }
ssal-database = { path = "../ssal-database" }